/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Copyright (c) 2026 Mark LaPointe <mark@cloudbsd.org>
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#include <sys/param.h>
#include <sys/stat.h>
#include <sys/sysctl.h>
#include <sys/unistd.h>
#include <err.h>
#include <errno.h>
#include <fcntl.h>
#include <libgen.h>
#include <paths.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <limits.h>

#include "emu.h"

extern int g_verbose;
extern int g_quiet;
extern enum emu_output_format g_output_format;

#define EMU_DEFAULT_ARCH	"amd64"
#define EMU_DEFAULT_CPU_LEVEL	1
#define EMU_DEFAULT_MEMORY	(512 * 1024 * 1024)	/* 512 MB */
#define EMU_DEFAULT_CPUS	1

/*
 * emu init - Initialize a new emulated instance
 *
 * Usage: emu init [--arch <arch>] [--cpu-level <level>] [--memory <size>]
 *                 [--cpus <count>] [--name <name>] [-v]
 */
int
emu_cmd_init(int argc, char *argv[])
{
	const char *arch = EMU_DEFAULT_ARCH;
	const char *name = NULL;
	char instance_dir[PATH_MAX];
	char config_file[PATH_MAX];
	char sysctl_name[PATH_MAX];
	int cpu_level = EMU_DEFAULT_CPU_LEVEL;
	uint64_t memory = EMU_DEFAULT_MEMORY;
	int cpus = EMU_DEFAULT_CPUS;
	int ch;
	int error;
	int fd;

	while ((ch = getopt(argc, argv, "a:c:m:n:v")) != -1) {
		switch (ch) {
		case 'a':
			arch = optarg;
			break;
		case 'c':
			cpu_level = atoi(optarg);
			if (cpu_level < 1 || cpu_level > 3) {
				fprintf(stderr, "Invalid CPU level (must be 1-3)\n");
				return (EINVAL);
			}
			break;
		case 'm':
			memory = strtoull(optarg, NULL, 0);
			if (memory < (64ULL * 1024 * 1024) ||
			    memory > (64ULL * 1024 * 1024 * 1024)) {
				fprintf(stderr, "Invalid memory size (must be 64M-64G)\n");
				return (EINVAL);
			}
			break;
		case 'n':
			name = optarg;
			break;
		case 'v':
			g_verbose = 1;
			break;
		default:
			return (EINVAL);
		}
	}

	argc -= optind;
	argv += optind;

	/* Generate instance name if not provided */
	if (name == NULL) {
		static int instance_counter = 0;
		char hostname[MAXHOSTNAMELEN];
		
		if (gethostname(hostname, sizeof(hostname)) != 0)
			strlcpy(hostname, "unknown", sizeof(hostname));
		
		snprintf(instance_dir, sizeof(instance_dir),
		    "%s-%s-%d", hostname, arch, ++instance_counter);
		name = instance_dir;
	}

	if (strlen(name) >= EMU_NAME_MAX) {
		fprintf(stderr, "Instance name too long (max %d)\n", EMU_NAME_MAX - 1);
		return (EINVAL);
	}

	if (g_verbose) {
		printf("Initializing emulated instance '%s'\n", name);
		printf("  Architecture: %s\n", arch);
		printf("  CPU Level: %d\n", cpu_level);
		printf("  Memory: %llu bytes\n", (unsigned long long)memory);
		printf("  CPUs: %d\n", cpus);
	}

	/* Create instance directory under XDG data directory */
	const char *data_dir = getenv("XDG_DATA_HOME");
	if (data_dir == NULL) {
		data_dir = getenv("HOME");
		if (data_dir == NULL) {
			fprintf(stderr, "HOME environment variable not set\n");
			return (ENOENT);
		}
		snprintf(instance_dir, sizeof(instance_dir),
		    "%s/.local/share/emu/instances/%s", data_dir, name);
	} else {
		snprintf(instance_dir, sizeof(instance_dir),
		    "%s/emu/instances/%s", data_dir, name);
	}

	/* Create instance directory */
	if (mkdirp(instance_dir, 0755) != 0) {
		fprintf(stderr, "Failed to create instance directory '%s': %s\n",
		    instance_dir, strerror(errno));
		return (errno);
	}

	/* Create configuration file */
	snprintf(config_file, sizeof(config_file), "%s/config", instance_dir);
	fd = open(config_file, O_WRONLY | O_CREAT | O_TRUNC, 0644);
	if (fd < 0) {
		fprintf(stderr, "Failed to create config file '%s': %s\n",
		    config_file, strerror(errno));
		return (errno);
	}

	dprintf(fd, "# Emulation Framework Instance Configuration\n");
	dprintf(fd, "# Generated by emu init\n");
	dprintf(fd, "name=%s\n", name);
	dprintf(fd, "arch=%s\n", arch);
	dprintf(fd, "cpu_level=%d\n", cpu_level);
	dprintf(fd, "memory=%llu\n", (unsigned long long)memory);
	dprintf(fd, "cpus=%d\n", cpus);
	dprintf(fd, "state=INITIALIZED\n");
	close(fd);

	if (g_verbose)
		printf("Configuration written to '%s'\n", config_file);

	/* Register instance with kernel module via sysctl */
	snprintf(sysctl_name, sizeof(sysctl_name),
	    "kern.emulation.instance.create");
	error = sysctlbyname(sysctl_name, NULL, NULL, __DECONST(void *, name), strlen(name));
	if (error != 0) {
		if (errno == EEXIST) {
			fprintf(stderr, "Instance '%s' already exists\n", name);
		} else if (errno == ENOENT) {
			fprintf(stderr, "Emulation framework not loaded (kern.emulation sysctl not found)\n");
		} else {
			fprintf(stderr, "Failed to register instance: %s\n", strerror(errno));
		}
		/* Don't fail - instance can still be used without kernel registration */
		if (g_verbose)
			printf("Warning: Kernel registration failed, continuing with userspace only\n");
	}

	if (!g_quiet) {
		printf("Instance '%s' initialized successfully\n", name);
		printf("  Directory: %s\n", instance_dir);
		printf("  Config: %s\n", config_file);
		printf("\nTo start the instance, run: emu start --name %s\n", name);
	}

	return (0);
}

/* Helper function to create directory with parent directories */
int
mkdirp(const char *path, mode_t mode)
{
	char tmp[PATH_MAX];
	char *p = NULL;
	size_t len;

	strlcpy(tmp, path, sizeof(tmp));
	len = strlen(tmp);
	
	if (tmp[len - 1] == '/')
		tmp[len - 1] = 0;
	
	for (p = tmp + 1; *p; p++) {
		if (*p == '/') {
			*p = 0;
			if (mkdir(tmp, mode) != 0 && errno != EEXIST)
				return (errno);
			*p = '/';
		}
	}
	
	if (mkdir(tmp, mode) != 0 && errno != EEXIST)
		return (errno);
	
	return (0);
}
