.if ${MK_ACPI} != "no"
SUBDIR+=	acpi
.endif
.if ${MK_APM} != "no"
SUBDIR+=	apm
SUBDIR+=	apmd
.endif
.if ${MK_EMULATION} != "no"
SUBDIR+=	emu
.endif
SUBDIR+=	boot0cfg
.if ${MK_TOOLCHAIN} != "no"
SUBDIR+=	btxld
.endif
SUBDIR+=	cpucontrol
SUBDIR+=	lptcontrol
SUBDIR+=	mptable
SUBDIR+=	pnpinfo
SUBDIR+=	spkrtest
SUBDIR+=	zzz
